apiVersion: v1
kind: Deployment
metadata: 
  name: nginx
  #replica set labels which can used under selectors to club the images
  labels:
    purpose: deployment-demo
    project: roboshop
    app: nginx
spec:
  replicas: 3
  # these are the labels replica set labels to create pod replicas, this should match pod labels
  selector:
    matchLabels:
      purpose: deployment-demo
      project: roboshop
      app: nginx
  #this is pod defnition template
  template:
    metadata:
      labels:
        purpose: deployment-demo
        project: roboshop
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
